-- 데이터베이스 생성
DROP DATABASE IF EXISTS hairshop;
CREATE DATABASE IF NOT EXISTS hairshop;
USE hairshop;

DELETE FROM designer ;



-- 리뷰 테이블 생성
CREATE TABLE `review` (
	`no`			INT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`reserved_no`	INT	NOT NULL	COMMENT '예약번호 UK,FK',
	`designer_no`	INT	NOT NULL	COMMENT '디자이너 FK',
	`content`	TEXT	NOT NULL	COMMENT '리뷰 내용',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '등록일자'
);



-- 회원 테이블 생성
CREATE TABLE `users` (
	`no`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(100)	NOT NULL	COMMENT '아이디',
	`password`	VARCHAR(100)	NOT NULL	COMMENT '비밀번호',
	`email`	VARCHAR(100)	NOT NULL	COMMENT '이메일',
	`full_name`	VARCHAR(100)	NOT NULL	COMMENT '이름',
	`birth`	DATETIME	NOT NULL	COMMENT '생년월일',
	`gender`	VARCHAR(100)	NOT NULL	COMMENT '성별',
	`nationality`	VARCHAR(100)	NOT NULL	COMMENT '국적',
	`phonenumber`	VARCHAR(100)	NOT NULL	COMMENT '전화번호',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '수정 일자'
);

-- 예약 테이블 생성
CREATE TABLE `reserved` (
	`no`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`user_no`	INT	NOT NULL	COMMENT '회원FK',
	`designer_no`	INT	NOT NULL	COMMENT '디자이너 FK',
	`style_no`	INT	NOT NULL	COMMENT '스타일 FK',
	`date`	TIMESTAMP	NOT NULL	COMMENT '예약 날짜',
	`time`	TIMESTAMP	NOT NULL	COMMENT '예약시간',
	`etc`	TEXT	NULL	COMMENT '특이 사항',
	`phonenumber`	INT	NOT NULL	COMMENT '전화번호',
	`price`	INT	NOT NULL	COMMENT '시술 가격',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '수정일자'
);
-- 헤어디자이너 테이블 생성
CREATE TABLE `designer` (
	`no`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(100)	NOT NULL	COMMENT '아이디',
	`password`	VARCHAR(100)	NOT NULL	COMMENT '비밀번호',
	`email`	VARCHAR(100)	NOT NULL	COMMENT '이메일',
	`full_name`	VARCHAR(100)	NOT NULL	COMMENT '미용실 이름',
	`birth`	TIMESTAMP	NOT NULL	COMMENT '생년월일',
	`gender`	VARCHAR(100)	NOT NULL	COMMENT '성별',
	`nationality`	VARCHAR(100)	NOT NULL	COMMENT '국적',
	`phonenumber`	VARCHAR(100)	NOT NULL	COMMENT '번호',
	`shop_name`	VARCHAR(100)	NOT NULL	COMMENT '매장명',
    `biz_num`	VARCHAR(100)	NOT NULL	COMMENT '사업자번호',
    `city`	VARCHAR(100)	NOT NULL	COMMENT '지역명',
    `district`	VARCHAR(100)	NOT NULL	COMMENT '구명',
    `addr_detail`	VARCHAR(100)	NOT NULL	COMMENT '상세주소',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록 일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '수정일자'
);
-- 헤어 시술 테이블 생성
CREATE TABLE `style` (
	`no`	INT	NOT NULL	COMMENT 'PK',
	`name`	VARCHAR(100)	NOT NULL	COMMENT '시술 이름',
	`price`	INT	NOT NULL	COMMENT '시술 가격',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록 일자'
);
-- 문의게시판 테이블 생성
CREATE TABLE `board` (
	`no`	INT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`user_no`	INT	NOT NULL	COMMENT '작성자  FK',
	`designer_no`	INT	NOT NULL	COMMENT '매장명FK',
	`title`	VARCHAR(100)	NOT NULL	COMMENT '제목',
	`content`	TEXT	NOT NULL	COMMENT '내용',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '수정일자'
);
-- 답글 테이블 생성
drop table if exists comment;


CREATE TABLE `comment` (
	`no`	INT	AUTO_INCREMENT primary key COMMENT 'PK',
	`board_no` int not null UNIQUE comment '게시판번호 FK',
	`designer_no`	INT	NOT NULL	COMMENT '작성자 FK',
	`content` TEXT not null comment '답글 내용',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '작성일자 ',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP	COMMENT '수정 일자'
);





ALTER TABLE `review` ADD CONSTRAINT `FK_reserved_TO_review_1` FOREIGN KEY (
	`reserved_no`
)
REFERENCES `reserved` (
	`no`
);
